### PR TITLE
feat(exports): export resolved and rejected names

### PR DESCRIPTION
**Pull request by noamokman**
Hi,
Added an export for the resolved and rejected names.
Useful when using [redux-axios-middleware](https://github.com/svrcekmichal/redux-axios-middleware) and you want to provide matching suffixes.

Thanks!

### CODE REVIEW

**Comment by noamokman** [comment]
Seems like tests fail because of old build code and configuration.. 😞

**Comment by alanrubin** [comment]
I have merged to master a PR updating babel to v6, eslint and mocha to the latest. Also making sure travis.yml runs with node 7. 

Regarding this PR, I have tried to fix the issues but realised it may not be the best way to provide this functionality - if users initialise the middleware with custom resolve/reject names then exporting the constants will return the default value (which is wrong).

How about assigning to the instantiated middleware the constant values used, for example:
```js
import promiseMiddleware from 'redux-simple-promise';

const promiseMiddleware = promiseMiddleware('_MY_RESOLVED', '_MY_REJECTED')

composeStoreWithMiddleware = applyMiddleware(
  promiseMiddleware
)(createStore);

// Retrieve constants used
console.log(promiseMiddleware.RESOLVED_NAME, promiseMiddleware.REJECTED_NAME)
```
What do you think ?

**Comment by noamokman** [comment]
Hi Alan,
Thanks for the feedback.

I pushed a new commit, rebased on your changes on master with the approach you mentioned.
I think this is our best course of action.
Would love to hear your thoughts.

P.S.
I haven't written any tests (YET), I wanted to run the implementation by you first.

P.P.S.
I think we need to bump dependencies to newer versions. flux-standard-action is on 0.6.0 and latest is 1.2.0

Thanks!

**Comment by noamokman** [comment]
@alanrubin Thoughts?

**Comment by noamokman** [comment]
Ping 🔔

**Comment by noamokman** [comment]
@alanrubin If you don't have the time, I would love to help out and maintain this repo for you.

**Pull request closed without merging**
